select  *from CBI_HR_PERSON where ename=''

select  *from CBI_HR_PERSON_KPI_YEAR where ename=''

SELECT
	r.VERSION_NM,
	r.需求量,
	s.供给量 
FROM
	( SELECT VERSION_NM, SUM( QTY ) 需求量 FROM CBI_CMC_SUPPLY_DEMAND WHERE DATA_TP = 'REQ_PLAN' and PRODUCT_CODE='IBI308' GROUP BY VERSION_NM ) r
	LEFT JOIN ( SELECT VERSION_NM, SUM( QTY ) 供给量 FROM CBI_CMC_SUPPLY_DEMAND WHERE DATA_TP = 'SUPPLY_PLAN' and PRODUCT_CODE='IBI308' GROUP BY VERSION_NM ) s ON r.VERSION_NM = s.VERSION_NM


-- 需求/供给分析	
SELECT
	r.STAT_MONTH,
	r.statMonth,
	r.reqPlan,
	s.supplyPlan 
FROM
	(
	SELECT RIGHT
		( STAT_MONTH, 2 ) statMonth,
		STAT_MONTH,
		SUM( QTY ) reqPlan 
	FROM
		CBI_CMC_SUPPLY_DEMAND_BACK 
	WHERE
		DATA_TP = 'REQ_PLAN' 
		AND PRODUCT_CODE = 'IBI308' 
		AND STR_TO_DATE( CONCAT( STAT_MONTH, '01' ), '%Y%m%d' )<= DATE_ADD( DATE_FORMAT( NOW(), '%Y%m%d' ), INTERVAL 24 MONTH ) 
		AND DATE_SUB( DATE_FORMAT( NOW(), '%Y%m%d' ), INTERVAL 1 MONTH )<= STR_TO_DATE( CONCAT( STAT_MONTH, '01' ), '%Y%m%d' ) 
		AND SEGMENT_NM = '临床' 
		-- AND PRODUCT_TP ='海外'
	GROUP BY
		STAT_MONTH 
	ORDER BY
		STAT_MONTH 
	) r
	LEFT JOIN (
	SELECT RIGHT
		( STAT_MONTH, 2 ) statMonth,
		STAT_MONTH,
		SUM( QTY ) supplyPlan 
	FROM
		CBI_CMC_SUPPLY_DEMAND_BACK
	WHERE
		DATA_TP = 'SUPPLY_PLAN' 
		AND PRODUCT_CODE = 'IBI308' 
		AND STR_TO_DATE( CONCAT( STAT_MONTH, '01' ), '%Y%m%d' )<= DATE_ADD( DATE_FORMAT( NOW(), '%Y%m%d' ), INTERVAL 24 MONTH ) 
		AND DATE_SUB( DATE_FORMAT( NOW(), '%Y%m%d' ), INTERVAL 1 MONTH )<= STR_TO_DATE( CONCAT( STAT_MONTH, '01' ), '%Y%m%d' ) 
		AND SEGMENT_NM = '临床' 
		-- AND PRODUCT_TP ='海外'
	GROUP BY
		STAT_MONTH 
	) s ON r.STAT_MONTH = s.STAT_MONTH



SELECT
	r.statMonth,
	r.reqPlan,
	s.supplyPlan 
FROM
	(
	SELECT RIGHT
		( STAT_MONTH, 2 ) statMonth,
		STAT_MONTH,
		SUM( QTY ) reqPlan 
	FROM
		CBI_CMC_SUPPLY_DEMAND 
	WHERE
		DATA_TP = 'REQ_PLAN' 
		AND STR_TO_DATE( CONCAT( STAT_MONTH, '01' ), '%Y%m%d' )<= DATE_ADD( DATE_FORMAT( NOW(), '%Y%m%d' ), INTERVAL 24 MONTH ) 
		AND DATE_SUB( DATE_FORMAT( NOW(), '%Y%m%d' ), INTERVAL 1 MONTH )<= STR_TO_DATE( CONCAT( STAT_MONTH, '01' ), '%Y%m%d' ) 
		AND PRODUCT_CODE = 'IBI308' 
		AND SEGMENT_NM = '商业化' 
	GROUP BY
		STAT_MONTH 
	ORDER BY
		STAT_MONTH 
	) r
	LEFT JOIN (
	SELECT RIGHT
		( STAT_MONTH, 2 ) statMonth,
		STAT_MONTH,
		SUM( QTY ) supplyPlan 
	FROM
		CBI_CMC_SUPPLY_DEMAND
	WHERE
		DATA_TP = 'SUPPLY_PLAN' 
		AND STR_TO_DATE( CONCAT( STAT_MONTH, '01' ), '%Y%m%d' )<= DATE_ADD( DATE_FORMAT( NOW(), '%Y%m%d' ), INTERVAL 24 MONTH ) 
		AND DATE_SUB( DATE_FORMAT( NOW(), '%Y%m%d' ), INTERVAL 1 MONTH )<= STR_TO_DATE( CONCAT( STAT_MONTH, '01' ), '%Y%m%d' ) 
		AND PRODUCT_CODE = 'IBI308' 
		AND SEGMENT_NM = '商业化' 
	GROUP BY
		STAT_MONTH 
	) s ON r.STAT_MONTH = s.STAT_MONTH






select VERSION_NM, DATE_SUB(STR_TO_DATE(CONCAT(STAT_MONTH,'01'),'%Y%m%d'),INTERVAL 25 MONTH),DATE_ADD(DATE_FORMAT(NOW(),'%Y%m%d'),INTERVAL 24 MONTH)
 from CBI_CMC_SUPPLY_DEMAND_BACK
 
 
select STR_TO_DATE(CONCAT(STAT_MONTH,'01'),'%Y%m%d'),STAT_MONTH,DATE_FORMAT( NOW(), '%Y%m%d' ),DATE_ADD( DATE_FORMAT( NOW(), '%Y%m%d' ), INTERVAL 12 MONTH ) from  CBI_CMC_SUPPLY_DEMAND_BACK

 
select RIGHT(VERSION_NM,2) VERSION_NM,SUM(QTY) STOCK_CLOSE from CBI_CMC_SUPPLY_DEMAND WHERE DATA_TP='STOCK_CLOSE' GROUP BY VERSION_NM 
 
 
select SUM(USABLE) USABLE from CBI_CMC_SUPPLY_DEMAND GROUP BY VERSION_NM 

select SUM(QTY) STOCK_SAFETY from CBI_CMC_SUPPLY_DEMAND WHERE DATA_TP='STOCK_SAFETY' GROUP BY VERSION_NM
 
select DATE_FORMAT( NOW(), '%Y%m%d' ) from dual
 
 -- 成品库存
SELECT RIGHT
	( o.STAT_MONTH, 2 ) statMonth,
	o.STOCK_CLOSE STOCK_CLOSE,
	h.USABLE USABLE
FROM
	(
	SELECT
		STAT_MONTH,
		SUM( QTY ) STOCK_CLOSE 
	FROM
		CBI_CMC_SUPPLY_DEMAND 
	WHERE
		DATA_TP = 'STOCK_CLOSE' 
		AND PRODUCT_CODE = 'IBI308' 
		AND STR_TO_DATE( CONCAT( STAT_MONTH, '01' ), '%Y%m%d' )<= DATE_ADD( DATE_FORMAT( NOW(), '%Y%m%d' ), INTERVAL 24 MONTH ) 
		AND DATE_SUB( DATE_FORMAT( NOW(), '%Y%m%d' ), INTERVAL 1 MONTH )<= STR_TO_DATE( CONCAT( STAT_MONTH, '01' ), '%Y%m%d' ) 
		AND SEGMENT_NM = '商业化' 
		-- AND PRODUCT_TP = '海外' 
	GROUP BY
		STAT_MONTH 
	ORDER BY
		STAT_MONTH 
	) o
	LEFT JOIN (
	SELECT
		STAT_MONTH,
		SUM( USABLE ) USABLE 
	FROM
		CBI_CMC_SUPPLY_DEMAND 
	WHERE
		STR_TO_DATE( CONCAT( STAT_MONTH, '01' ), '%Y%m%d' )<= DATE_ADD( DATE_FORMAT( NOW(), '%Y%m%d' ), INTERVAL 24 MONTH ) 
		AND DATE_SUB( DATE_FORMAT( NOW(), '%Y%m%d' ), INTERVAL 1 MONTH )<= STR_TO_DATE( CONCAT( STAT_MONTH, '01' ), '%Y%m%d' ) 
		AND PRODUCT_CODE = 'IBI308' 
		AND SEGMENT_NM = '商业化' 
		-- AND PRODUCT_TP = '海外' 
	GROUP BY
		STAT_MONTH 
	ORDER BY
		STAT_MONTH 
	) h ON o.STAT_MONTH = h.STAT_MONTH
	


select o.VERSION_NM,o.STOCK_CLOSE from (select SUM(QTY) STOCK_SAFETY from CBI_CMC_SUPPLY_DEMAND WHERE DATA_TP='STOCK_SAFETY' GROUP BY VERSION_NM) AS o
 
 

 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 