server:
  port: 8080
  servlet:
    context-path: /tree
spring:
  datasource:
    url: jdbc:p6spy:mysql://10.0.2.12:3306/tree?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&testWhileIdle=false
    username: root
    password: root123
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    # testWhileIdle: false
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  redis:
    # redis服务器资质
    host: 10.0.2.32
    # redis服务器连接端口
    port: 6379
    # redis服务器连接密码（默认为空）
    password:
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池中的最小空闲连接
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
    # Redis数据库索引（默认为0）,此处设置为数据库1 redis有16个数据库
    database: 1
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.zcc.study.mybatis.redis.domain
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0