# 控制台输出log4j-spring.properties格式配置
# INFO是日志输出级别，共有5级 FATAL ERROR WARN INFO DEBUG
log4j.rootCategory=INFO, stdout
log4j.appender.stdout = org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Target = System.out
log4j.appender.stdout.layout = org.apache.log4j.PatternLayout
log4j.appender.file.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss,SSS} %5p %c{1}:%L - %m%n
# 配置输出日志到文件log4j-spring.properties格式配置
# log4j.rootCategory=INFO, stdout, file
# log4j.appender.file=org.apache.log4j.DailyRollingFileAppender
# 输出到logs/all.log文件中
# log4j.appender.file.file=logs/all.log
# log4j.appender.file.DatePattern='.'yyyy-MM-dd
# log4j.appender.file.layout=org.apache.log4j.PatternLayout
# log4j.appender.file.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss,SSS} %5p %c{1}:%L - %m%n
# org.apache.log4j.ConsoleAppender（控制台），
# org.apache.log4j.FileAppender（文件），
# org.apache.log4j.DailyRollingFileAppender（每天产生一个日志文件），
# org.apache.log4j.RollingFileAppender（文件大小到达指定尺寸的时候产生一个新的文件），
# org.apache.log4j.WriterAppender（将日志信息以流格式发送到任意指定的地方）
